# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
